// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzcsfpmagakyriigkgzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6Y3NmcG1hZ2FreXJpaWdrZ3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODU2MTUsImV4cCI6MjA2OTA2MTYxNX0.8uvsldNPpgI98c8WKDhtHvKNNx8Wxmd_1D8TCevAWnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});